#!/bin/bash

# Check if build folder exists, if not create it
if [ ! -d "./builds" ]; then
    echo "Build folder does not exist. Creating it..."
    mkdir -p "./builds"
fi

# Build the Docker image
docker build -t backend-aarch64-musl .

# Create a temporary container
docker create --name temp backend-aarch64-musl

# Copy the binary from the container
docker cp temp:/backend ./builds/backend

# Remove the temporary container
docker rm temp

echo "Binary extracted as $BINARY_NAME"